services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

  directus:
    image: directus/directus:11.12.0
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT:-8055}:8055"
    env_file:
      - .env.local
    environment:
      WEBSOCKETS_ENABLED: "true"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./schema:/directus/schema
    restart: unless-stopped

volumes:
  db_data:
